/**
 * Core type definitions for Chrome Tab Killer extension.
 * All data structures are strongly typed for reliability and maintainability.
 */

// ============================================================================
// Configuration Types
// ============================================================================

export interface TargetSites {
  [domain: string]: boolean;
}

export interface ExtensionConfig {
  autoDiscardEnabled: boolean;
  targetSites: TargetSites;
  discardInterval: DiscardInterval;
  idleTabThreshold: number; // hours, 0 = disabled
  dataRetentionDays: number; // days to keep telemetry data
}

export type DiscardInterval = 5 | 10 | 15 | 30;

export const DEFAULT_CONFIG: ExtensionConfig = {
  autoDiscardEnabled: true,
  targetSites: {},
  discardInterval: 10,
  idleTabThreshold: 24,
  dataRetentionDays: 180,
};

// Suggested sites shown as examples in the dashboard (not enabled by default)
export const SUGGESTED_SITES = ['sharepoint', 'slack', 'asana', 'quicksight'] as const;

// ============================================================================
// Telemetry Types
// ============================================================================

export type TabEventType =
  | 'created'
  | 'activated'
  | 'deactivated'
  | 'updated'
  | 'removed'
  | 'discarded'
  | 'reloaded';

export interface TabEvent {
  id?: number; // Auto-generated by IndexedDB
  tabId: number;
  eventType: TabEventType;
  timestamp: number;
  url?: string;
  title?: string;
  windowId?: number;
  index?: number;
  openerTabId?: number | null;
  activeTime?: number;
  manual?: boolean;
  reason?: DiscardReason;
  timeSinceDiscard?: number;
  windowClosing?: boolean;
}

export interface TabMetadata {
  tabId: number;
  url?: string;
  domain?: string;
  title?: string;
  windowId?: number;
  openerTabId?: number | null;
  createdAt?: number;
  lastUpdated?: number;
  lastActive?: number;
  activationCount: number;
  totalActiveTime: number;
  wasDiscarded: boolean;
  discardedAt?: number | null;
}

export type DiscardReason = 'site-match' | 'idle' | 'manual';

export interface DiscardedTabInfo {
  url: string;
  domain: string;
  title: string;
  timeSinceLastActive: number | null;
  reason?: DiscardReason;
}

export interface DiscardEvent {
  id?: number; // Auto-generated by IndexedDB
  timestamp: number;
  discardedCount: number;
  totalTabs: number;
  tabs: DiscardedTabInfo[];
}

export interface TelemetryStats {
  totalEvents: number;
  totalTabs: number;
  totalDiscards: number;
}

export interface ExportedData {
  exportDate: string;
  tabEvents: TabEvent[];
  tabMetadata: TabMetadata[];
  discardEvents: DiscardEvent[];
}

// ============================================================================
// Message Types (for chrome.runtime.sendMessage)
// ============================================================================

export type MessageAction =
  | 'toggleAutoDiscard'
  | 'updateTargetSites'
  | 'updateInterval'
  | 'updateIdleThreshold'
  | 'discardAll'
  | 'exportTelemetry'
  | 'clearTelemetry'
  | 'getTelemetryStats';

export interface BaseMessage {
  action: MessageAction;
}

export interface ToggleAutoDiscardMessage extends BaseMessage {
  action: 'toggleAutoDiscard';
  enabled: boolean;
}

export interface UpdateTargetSitesMessage extends BaseMessage {
  action: 'updateTargetSites';
  targetSites: TargetSites;
}

export interface UpdateIntervalMessage extends BaseMessage {
  action: 'updateInterval';
  interval: DiscardInterval;
}

export interface UpdateIdleThresholdMessage extends BaseMessage {
  action: 'updateIdleThreshold';
  threshold: number;
}

export interface DiscardAllMessage extends BaseMessage {
  action: 'discardAll';
}

export interface ExportTelemetryMessage extends BaseMessage {
  action: 'exportTelemetry';
}

export interface ClearTelemetryMessage extends BaseMessage {
  action: 'clearTelemetry';
}

export interface GetTelemetryStatsMessage extends BaseMessage {
  action: 'getTelemetryStats';
}

export type ExtensionMessage =
  | ToggleAutoDiscardMessage
  | UpdateTargetSitesMessage
  | UpdateIntervalMessage
  | UpdateIdleThresholdMessage
  | DiscardAllMessage
  | ExportTelemetryMessage
  | ClearTelemetryMessage
  | GetTelemetryStatsMessage;

// ============================================================================
// Response Types
// ============================================================================

export interface SuccessResponse<T = unknown> {
  success: true;
  data?: T;
  count?: number;
  stats?: TelemetryStats;
}

export interface ErrorResponse {
  success: false;
  error: string;
}

export type MessageResponse<T = unknown> = SuccessResponse<T> | ErrorResponse;

// ============================================================================
// Storage Types
// ============================================================================

export interface StorageData {
  autoDiscardEnabled?: boolean;
  targetSites?: TargetSites;
  discardInterval?: DiscardInterval;
  idleTabThreshold?: number;
  dataRetentionDays?: number;
  lastRun?: number;
  lastDiscardedCount?: number;
}

// ============================================================================
// Validation Helpers
// ============================================================================

export function isValidDiscardInterval(value: number): value is DiscardInterval {
  return [5, 10, 15, 30].includes(value);
}

export function isValidIdleThreshold(value: number): boolean {
  return Number.isInteger(value) && value >= 0 && value <= 720; // Max 30 days
}

export function isValidDataRetentionDays(value: number): boolean {
  return Number.isInteger(value) && value >= 1 && value <= 365;
}

export function isValidDomain(domain: string): boolean {
  if (domain.length === 0 || domain.length > 253) {
    return false;
  }
  // Basic domain validation: no spaces, at least one character
  const domainPattern = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i;
  return domainPattern.test(domain);
}

// ============================================================================
// Alarm Constants
// ============================================================================

export const ALARM_NAME = 'autoDiscardAlarm';
export const RETENTION_ALARM_NAME = 'dataRetentionAlarm';
